/**
 * Post-processes `expo export` output into an installable PWA.
 *
 * Expo emits content-hashed bundle filenames that change on every build, so
 * the service worker's precache list is generated here from the real export
 * rather than hand-maintained.
 *
 * Usage: node scripts/build-pwa.mjs [outputDir]   (default: dist)
 */
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..');
const outDir = path.resolve(root, process.argv[2] || 'dist');

/* ----------------------------------------------------------- collect files */

function walk(dir, base = dir) {
  const out = [];
  for (const entry of readdirSync(dir)) {
    const full = path.join(dir, entry);
    if (statSync(full).isDirectory()) out.push(...walk(full, base));
    else out.push('/' + path.relative(base, full).split(path.sep).join('/'));
  }
  return out;
}

const allFiles = walk(outDir);

// Precache the app shell: the HTML entry, the JS bundle(s), and the icons.
// Fonts and navigation images are picked up at runtime instead, to keep the
// install payload small.
const precache = allFiles.filter(
  (f) =>
    f === '/index.html' ||
    f === '/favicon.ico' ||
    f === '/manifest.webmanifest' ||
    f.startsWith('/icons/') ||
    /^\/_expo\/static\/js\/web\/.+\.js$/.test(f)
);

if (!precache.some((f) => f.endsWith('.js'))) {
  console.error('✗ No JS bundle found in the export — aborting.');
  process.exit(1);
}

// Version the caches by the content of everything we precache, so a new build
// automatically invalidates the old cache and no stale shell survives.
const hash = createHash('sha256');
for (const f of [...precache].sort()) {
  hash.update(f);
  hash.update(readFileSync(path.join(outDir, f)));
}
const version = hash.digest('hex').slice(0, 12);

/* -------------------------------------------------------- service worker */

const sw = `/**
 * Service worker for MAC Multimedia Exams.
 * GENERATED by scripts/build-pwa.mjs — do not edit by hand.
 *
 * Strategy
 *   API requests   never cached (network only)
 *   navigations    network first, falling back to the cached app shell
 *   static assets  cache first (filenames are content-hashed)
 */
const VERSION = '${version}';
const SHELL_CACHE = 'shell-' + VERSION;
const ASSET_CACHE = 'assets-' + VERSION;
const SHELL_URL = '/index.html';

const PRECACHE = ${JSON.stringify(precache.sort(), null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil(
    (async () => {
      const cache = await caches.open(SHELL_CACHE);
      // Bypass the HTTP cache so a redeploy can't precache a stale shell.
      await cache.addAll(PRECACHE.map((url) => new Request(url, { cache: 'reload' })));
      await self.skipWaiting();
    })()
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    (async () => {
      const keep = new Set([SHELL_CACHE, ASSET_CACHE]);
      for (const key of await caches.keys()) {
        if (!keep.has(key)) await caches.delete(key);
      }
      await self.clients.claim();
    })()
  );
});

/**
 * Anything that isn't a same-origin static asset must go straight to the
 * network. Exam questions, attempts and auth responses are user-specific and
 * must never be written to a shared cache.
 */
function isApiRequest(url) {
  return url.pathname.startsWith('/api/');
}

function isStaticAsset(url) {
  return (
    url.pathname.startsWith('/_expo/') ||
    url.pathname.startsWith('/icons/') ||
    url.pathname.startsWith('/assets/') ||
    url.pathname === '/favicon.ico' ||
    url.pathname === '/manifest.webmanifest'
  );
}

self.addEventListener('fetch', (event) => {
  const { request } = event;

  if (request.method !== 'GET') return;

  const url = new URL(request.url);

  // Cross-origin (including the API on another host) and same-origin /api/:
  // let the network handle it, uncached.
  if (url.origin !== self.location.origin || isApiRequest(url)) return;

  // Navigations: try the network so users get the newest deploy, fall back to
  // the cached shell when offline. The SPA router takes over from there.
  if (request.mode === 'navigate') {
    event.respondWith(
      (async () => {
        try {
          const fresh = await fetch(request);
          const cache = await caches.open(SHELL_CACHE);
          cache.put(SHELL_URL, fresh.clone());
          return fresh;
        } catch {
          const cached = await caches.match(SHELL_URL);
          return cached || Response.error();
        }
      })()
    );
    return;
  }

  // Static assets: cache first. Bundle names are content-hashed, so a cache
  // hit is always the right version.
  if (isStaticAsset(url)) {
    event.respondWith(
      (async () => {
        const cached = await caches.match(request);
        if (cached) return cached;
        try {
          const fresh = await fetch(request);
          if (fresh.ok && fresh.type === 'basic') {
            const cache = await caches.open(ASSET_CACHE);
            cache.put(request, fresh.clone());
          }
          return fresh;
        } catch (err) {
          return cached || Response.error();
        }
      })()
    );
  }
});

// Lets the page trigger an immediate update instead of waiting for a restart.
self.addEventListener('message', (event) => {
  if (event.data === 'SKIP_WAITING') self.skipWaiting();
});
`;

writeFileSync(path.join(outDir, 'service-worker.js'), sw);

/* --------------------------------------------------------- host redirects */

// SPA fallback for static hosts, so deep links don't 404 on refresh.
writeFileSync(path.join(outDir, '_redirects'), '/*    /index.html   200\n');

// Netlify cache headers. Without no-cache on the service worker a browser can
// pin an old one and never pick up a redeploy.
writeFileSync(
  path.join(outDir, '_headers'),
  [
    '/service-worker.js',
    '  Cache-Control: no-cache',
    '/index.html',
    '  Cache-Control: no-cache',
    '/manifest.webmanifest',
    '  Cache-Control: no-cache',
    '  Content-Type: application/manifest+json; charset=utf-8',
    '/_expo/static/*',
    '  Cache-Control: public, max-age=31536000, immutable',
    '',
  ].join('\n')
);

writeFileSync(
  path.join(outDir, 'vercel.json'),
  JSON.stringify(
    {
      rewrites: [{ source: '/(.*)', destination: '/index.html' }],
      headers: [
        {
          source: '/service-worker.js',
          headers: [{ key: 'Cache-Control', value: 'no-cache' }],
        },
        {
          source: '/_expo/static/(.*)',
          headers: [{ key: 'Cache-Control', value: 'public, max-age=31536000, immutable' }],
        },
      ],
    },
    null,
    2
  ) + '\n'
);

/* ------------------------------------------------------------------ report */

console.log(`✓ PWA ready in ${path.relative(root, outDir) || '.'}`);
console.log(`  cache version   ${version}`);
console.log(`  precached       ${precache.length} files`);
precache.forEach((f) => console.log(`                  ${f}`));
console.log(`  host config     _redirects, _headers, vercel.json`);
